#ifndef DEFS_H
#define DEFS_H

#define BUFFER_SIZE 8192
#define FILE_CHUNK_SIZE 64*1024
#define MAX_BACKLOG 1024
#define MAX_EVENTS 64
#define MIN_UPSTREAM_CONNECTIONS 16
#define MAX_UPSTREAM_CONNECTIONS 1024
#define SERVER_NAME "rgnx/0.0.1"

#endif

